// packages/gantt_chart/lib/src/gantt_chart_widget.dart
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:legacy_gantt_chart/src/models/legacy_gantt_dependency.dart';
import 'package:flutter/scheduler.dart';
import 'package:provider/provider.dart';
import 'models/legacy_gantt_task.dart';
import 'models/legacy_gantt_theme.dart';
import 'models/legacy_gantt_row.dart';
import 'axis_painter.dart';
import 'legacy_gantt_controller.dart';
import 'legacy_gantt_view_model.dart';
import 'bars_collection_painter.dart';
import 'package:legacy_gantt_protocol/legacy_gantt_protocol.dart';

import 'cursor_painter.dart';
import 'widgets/resource_histogram.dart';
import 'models/work_calendar.dart';

/// Defines the type of progress indicator to display during loading.
enum GanttLoadingIndicatorType {
  /// A circular progress indicator in the center of the chart.
  circular,

  /// A linear progress indicator at the top or bottom of the chart.
  linear,
}

/// Defines the position for the linear progress indicator.
enum GanttLoadingIndicatorPosition {
  /// Positions the linear indicator at the top of the chart area.
  top,

  /// Positions the linear indicator at the bottom of the chart area.
  bottom,
}

/// The main widget for displaying a Gantt chart.
///
/// This widget is responsible for rendering the timeline, task bars, and dependencies.
/// It handles user interactions such as dragging, resizing, and creating tasks and dependencies.
///
/// It can be used with a static list of data or dynamically with a [LegacyGanttController].
///
/// **Horizontal zoom:** Use [horizontalZoomFactor] (≥ 1.0) for more timeline detail. When it is
/// greater than 1, the chart scrolls horizontally inside the widget. Prefer this over wrapping
/// the chart in another horizontal [SingleChildScrollView]. With [allowHorizontalZoomGestures],
/// use Ctrl+scroll or Cmd+scroll (vertical wheel) or a trackpad pinch to zoom; listen with
/// [onHorizontalZoomFactorChanged] to sync parent state.
class LegacyGanttChartWidget extends StatefulWidget {
  /// The list of [LegacyGanttTask] objects to display on the chart.
  /// This is ignored if a [controller] or [tasksFuture] is provided.
  final List<LegacyGanttTask>? data;

  /// A list of dependencies to draw between tasks.
  /// This is ignored if a [controller] is provided.
  final List<LegacyGanttTaskDependency>? dependencies;

  /// A list of conflict indicators to draw on the chart. These are typically
  /// generated by a conflict detection algorithm.
  final List<LegacyGanttTask>? conflictIndicators;

  /// A list of tasks to be rendered as background highlights, such as holidays
  /// or weekends. These tasks should have `isTimeRangeHighlight` set to `true`.
  /// This is ignored if a [controller] is provided.
  final List<LegacyGanttTask>? holidays;

  /// The list of [LegacyGanttRow]s that are currently visible in the chart's viewport.
  /// This is used to determine which rows to render.
  final List<LegacyGanttRow> visibleRows;

  /// A callback function invoked when the user's cursor hovers over a task.
  ///
  /// Provides the [LegacyGanttTask] being hovered and the global position of the cursor.
  /// Useful for showing custom tooltips or hover effects.
  final Function(LegacyGanttTask?, Offset globalPosition)? onTaskHover;

  /// A scroll controller for the vertical scrolling of the Gantt chart.
  ///
  /// This should be the same controller used by an accompanying data grid (e.g., `GanttGrid`)
  /// to ensure that the chart and the grid scroll in sync.
  final ScrollController? scrollController;

  /// The height of the timeline axis header at the top of the chart.
  final double? axisHeight;

  /// Defines the height of each row based on task overlaps.
  ///
  /// This map keys a [LegacyGanttRow.id] to an integer representing the maximum
  /// number of concurrent tasks to display vertically in that row.
  ///
  /// * **Calculation:** The total height for a given row is calculated as
  ///   `rowHeight * rowMaxStackDepth[rowId]`.
  /// * **Conflicts:** If more tasks overlap than this value allows, the chart
  ///   will render a conflict indicator (a red, patterned bar) if `showConflicts` is enabled.
  final Map<String, int> rowMaxStackDepth;

  /// The height of a single task bar lane within a row. The total height of a
  /// [LegacyGanttRow] is `rowHeight * stackDepth`.
  final double rowHeight;

  /// The theme data that defines the colors and styles for the chart's elements.
  /// If not provided, a default theme is derived from the ambient [ThemeData].
  final LegacyGanttTheme? theme;

  /// The start of the visible date range, expressed as milliseconds since the Unix epoch.
  ///
  /// This determines the leftmost edge of the chart's viewport.
  /// * If a [controller] is provided, this property is ignored as the controller manages the viewport.
  /// * If [gridMin] is null and no controller is used, the chart defaults to the earliest start date found in [data].
  final double? gridMin;

  /// The end of the visible date range, expressed as milliseconds since the Unix epoch.
  ///
  /// This determines the rightmost edge of the chart's viewport.
  /// * If a [controller] is provided, this property is ignored as the controller manages the viewport.
  /// * If [gridMax] is null and no controller is used, the chart defaults to the latest end date found in [data].
  final double? gridMax;

  /// The absolute start of the entire possible date range for the chart.
  /// This is used by the timeline axis to determine its overall width.
  final double? totalGridMin; // The start of the entire dataset's time range

  /// The absolute end of the entire possible date range for the chart.
  final double? totalGridMax; // The end of the entire dataset's time range

  /// A callback function invoked when a user taps or clicks on a task bar.
  final Function(LegacyGanttTask)? onPressTask;

  /// Enables or disables the ability to drag and drop tasks to change their time or row.
  final bool enableDragAndDrop;

  /// Enables or disables the ability to resize tasks by dragging their start or end handles.
  final bool enableResize;

  /// A future that resolves to the list of tasks to display.
  /// This is ignored if a [controller] is provided.
  final Future<List<LegacyGanttTask>>? tasksFuture;

  /// A future that resolves to a list of holiday/highlight tasks.
  /// This is ignored if a [controller] is provided.
  final Future<List<LegacyGanttTask>>? holidaysFuture;

  /// A controller to programmatically manage the Gantt chart's state, including
  /// the visible date range and dynamically loaded data. When a controller is
  /// provided, properties like `data`, `holidays`, `gridMin`, and `gridMax` are
  /// ignored as they are managed by the controller.
  final LegacyGanttController? controller;

  /// A builder function to create a completely custom widget for a task bar.
  ///
  /// If this is provided, the default task bar painting is skipped, and this widget is
  /// rendered instead. This gives full control over the appearance and behavior of a task.
  /// This cannot be used simultaneously with [taskContentBuilder].
  final Widget Function(LegacyGanttTask task)? taskBarBuilder;

  /// A builder to create custom content *inside* the default task bar.
  ///
  /// This is useful for adding custom icons, text, or progress indicators while
  /// retaining the default bar's shape, color, and drag/resize handles.
  /// This cannot be used simultaneously with [taskBarBuilder].
  final Widget Function(LegacyGanttTask task)? taskContentBuilder;

  /// A callback function that is invoked when a task is updated through dragging or resizing.
  ///
  /// Provides the updated [LegacyGanttTask] and its new `start` and `end` times.
  final Function(LegacyGanttTask task, DateTime newStart, DateTime newEnd)? onTaskUpdate;

  /// A callback function that is invoked when a task move changes the row assignment.
  ///
  /// This is only emitted when [enableVerticalTaskDrag] is true and the user drops
  /// a task onto a different row.
  final Function(LegacyGanttTask task, DateTime newStart, DateTime newEnd, String newRowId)? onTaskMove;

  /// A callback function invoked when a batch of tasks are updated.
  final Function(List<(LegacyGanttTask, DateTime, DateTime)>)? onBulkTaskUpdate;

  /// A callback invoked when the visible time range changes due to user panning/scrolling.
  ///
  /// This is important when you pass [gridMin]/[gridMax] from external state (controlled mode).
  /// In that case, update your external state in this callback; otherwise the next rebuild
  /// will restore the old range and the chart will appear to not scroll horizontally.
  final Function(DateTime start, DateTime end)? onVisibleRangeChanged;

  /// Enables moving tasks vertically between rows while dragging.
  ///
  /// When enabled, horizontal dragging continues to adjust the task dates, while
  /// the pointer's vertical position determines the target row. Row changes are
  /// reported through [onTaskMove].
  final bool enableVerticalTaskDrag;

  /// A callback function invoked when a user double-taps or double-clicks on a task bar.
  ///
  /// Provides the [LegacyGanttTask] that was double-tapped.
  final Function(LegacyGanttTask task)? onTaskDoubleClick;

  /// A callback function that is invoked when a task is deleted.
  final Function(LegacyGanttTask task)? onTaskDelete;

  /// A function to format the date/time shown in the tooltip when resizing a task.
  final String Function(DateTime)? resizeTooltipDateFormat;

  /// A callback that is triggered when a user clicks on an empty space in the
  /// chart. This can be used to initiate the creation of a new task.
  final Function(String rowId, DateTime time)? onEmptySpaceClick;

  /// A callback that is triggered when a user completes a draw action (drag) in the chart
  /// while the Draw tool is active.
  ///
  /// Provides the start and end times of the drawn range, and the row ID.
  final Function(DateTime start, DateTime end, String rowId)? onTaskDrawEnd;

  /// A callback that is invoked when a new dependency is created via the Draw Dependencies tool.
  final Function(LegacyGanttTaskDependency dependency)? onDependencyAdd;

  /// Callback when a task is secondary tapped (e.g. right click).
  final Function(LegacyGanttTask task, Offset position)? onTaskSecondaryTap;

  /// Callback when a task is long pressed.
  final Function(LegacyGanttTask task, Offset position)? onTaskLongPress;

  /// The background color of the tooltip that appears during drag or resize operations.
  /// If not provided, it defaults to the theme's `barColorPrimary`.
  final Color? resizeTooltipBackgroundColor;

  /// The font color of the tooltip that appears during drag or resize operations.
  /// If not provided, it's automatically determined for contrast against the
  /// tooltip's background color.
  final Color? resizeTooltipFontColor;

  /// The width of the resize handles at the start and end of a task bar.
  final double resizeHandleWidth;

  /// A builder function to customize the labels displayed on the timeline axis.
  ///
  /// This function is called for each label on the timeline and provides the
  /// [DateTime] of the label and the current [Duration] of the tick interval.
  /// This allows for flexible formatting, such as displaying month names,
  /// fiscal year quarters, or any other custom representation.
  ///
  /// Example:
  /// ```dart
  /// timelineAxisLabelBuilder: (DateTime date, Duration interval) {
  ///   if (interval.inDays > 20) {
  ///     return DateFormat('MMM yyyy').format(date); // Display month and year
  ///   } else {
  ///     return DateFormat('d MMM').format(date); // Display day and month
  ///   }
  /// }
  /// ```
  final String Function(DateTime, Duration)? timelineAxisLabelBuilder;

  /// Controls how the timeline axis/grid should be segmented (day/week/month/year).
  ///
  /// - If [TimelineViewMode.auto], the chart uses an adaptive tick-step algorithm.
  /// - Otherwise, it draws major boundary lines for the selected mode.
  ///
  /// Note: If you provide [timelineAxisHeaderBuilder], you can (and should) use the
  /// same mode inside your custom header painter for consistent boundaries/label centering.
  final TimelineViewMode timelineViewMode;

  /// Controls where labels are placed relative to major boundaries.
  ///
  /// Defaults:
  /// - week: on boundary
  /// - day/month/year: between boundaries
  final TimelineLabelPlacement? timelineLabelPlacement;

  /// Stroke width for grid lines in auto mode.
  final double gridLineStrokeWidth;

  /// Stroke width for major boundary lines in non-auto view modes.
  final double majorGridLineStrokeWidth;

  /// A builder function to create a completely custom widget for the timeline header.
  ///
  /// If this is provided, the default timeline header painting is skipped, and this
  /// widget is rendered instead. This gives you full control over the appearance
  /// and behavior of the timeline header.
  ///
  /// The builder provides the following arguments:
  /// - `context`: The build context.
  /// - `scale`: A function that converts a `DateTime` to its corresponding horizontal (x-axis) pixel value.
  /// - `visibleDomain`: The currently visible date range.
  /// - `totalDomain`: The total date range of the entire chart.
  /// - `theme`: The current Gantt chart theme.
  /// - `totalContentWidth`: The total width of the chart's content area.
  final Widget Function(
    BuildContext context,
    double Function(DateTime) scale,
    List<DateTime> visibleDomain,
    List<DateTime> totalDomain,
    LegacyGanttTheme theme,
    double totalContentWidth,
  )? timelineAxisHeaderBuilder;

  /// Optional builder to render a custom widget when the data set is empty.
  /// Replaces the default "No data to display" text.
  final WidgetBuilder? emptyStateBuilder;

  /// If set to `true`, the chart will display the empty rows provided via
  /// [visibleRows] even when there are no tasks.
  ///
  /// Defaults to `false`, which shows the [emptyStateBuilder] or a default "No data to display" message.
  final bool showEmptyRows;

  /// An optional fixed height for the Gantt chart widget.
  ///
  /// If provided, the widget will render with this explicit height. This is
  /// particularly useful when placing the Gantt chart inside a `SingleChildScrollView`
  /// to make it vertically scrollable. The user is responsible for calculating
  /// the appropriate height based on the number of rows and their content.
  ///
  /// If `null`, the widget will attempt to size itself based on the available
  /// constraints, either expanding to fill a parent (like `Expanded`) or
  /// calculating its intrinsic height if given unconstrained vertical space.
  final double? height;

  /// The type of progress indicator to display when loading data with a [controller].
  ///
  /// Defaults to [GanttLoadingIndicatorType.circular].
  final GanttLoadingIndicatorType loadingIndicatorType;

  /// The position of the [GanttLoadingIndicatorType.linear] progress indicator.
  ///
  /// This is only applicable if [loadingIndicatorType] is set to
  /// [GanttLoadingIndicatorType.linear].
  /// Defaults to [GanttLoadingIndicatorPosition.top].
  final GanttLoadingIndicatorPosition loadingIndicatorPosition;

  /// Defines the height of the linear loading indicator.
  /// Defaults to 4.0.
  final double linearProgressHeight;

  /// The days of the week to be highlighted as weekends.
  ///
  /// This list should contain integers representing the days of the week,
  /// where Monday is 1 and Sunday is 7.
  /// Defaults to [DateTime.saturday] and [DateTime.sunday].
  final List<int> weekendDays;

  /// The color used to highlight weekends in the chart background.
  ///
  /// If not provided, it defaults to a semi-transparent shade of the
  /// theme's `onSurface` color.
  /// The color used to highlight weekends in the chart background.
  ///
  /// If not provided, it defaults to a semi-transparent shade of the
  /// theme's `onSurface` color.
  final Color? weekendColor;

  /// The synchronization client for multiplayer features.
  final GanttSyncClient? syncClient;

  /// A function to group tasks for conflict detection.
  final Object? Function(LegacyGanttTask task)? taskGrouper;

  /// A scroll controller for the horizontal scrolling of the Gantt chart.
  /// This is used internally to allow programmatic scrolling, for example,
  /// to bring a focused task into view.
  ///
  /// When [horizontalZoomFactor] is greater than `1.0`, horizontal scrolling is
  /// handled inside this widget; pass the same controller here so you can sync
  /// or jump programmatically. If omitted, an internal controller is created.
  final ScrollController? horizontalScrollController;

  /// Horizontal zoom: `1.0` maps the full [totalGridMin]–[totalGridMax] range to
  /// the viewport width. Values above `1.0` use more pixels per unit time and
  /// enable horizontal scrolling inside the chart.
  ///
  /// Avoid wrapping the chart in an extra horizontal [SingleChildScrollView]
  /// when this is above `1.0`; that would nest two horizontal scroll views.
  final double horizontalZoomFactor;

  /// Minimum for [horizontalZoomFactor] (must be ≥ `1.0`).
  final double horizontalZoomMin;

  /// Maximum for [horizontalZoomFactor] (must be greater than [horizontalZoomMin]).
  final double horizontalZoomMax;

  /// When true, Ctrl+scroll / Cmd+scroll (vertical wheel) and trackpad pinch
  /// adjust zoom within [horizontalZoomMin]–[horizontalZoomMax].
  final bool allowHorizontalZoomGestures;

  /// Notified when a built-in gesture changes the zoom factor. You can update
  /// parent state here to keep [horizontalZoomFactor] in sync (controlled mode).
  final ValueChanged<double>? onHorizontalZoomFactorChanged;

  /// A callback invoked when an action (like focusing a task via keyboard)
  /// requires a row to become visible (e.g., by expanding a collapsed parent).
  /// The consumer of this widget is responsible for updating its state to make the row visible.
  final Function(String rowId)? onRowRequestVisible;

  /// The ID of the task that currently has keyboard focus.
  final String? focusedTaskId;

  /// A callback invoked when the focused task changes due to user interaction.
  final Function(String? taskId)? onFocusChange;

  /// A builder function to create custom resize handles that appear next to a focused task.
  ///
  /// The builder provides the `task` and a `part` enum (`TaskPart.startHandle` or `TaskPart.endHandle`)
  /// to allow for different widgets for the start and end handles. If this is `null`, no
  /// external handles are shown for focused tasks.
  final Widget Function(LegacyGanttTask task, TaskPart part, LegacyGanttViewModel vm, double handleWidth)?
      focusedTaskResizeHandleBuilder;

  /// The width of the floating resize handles that appear on a focused task.
  /// This value is passed to the [focusedTaskResizeHandleBuilder]. Defaults to `24.0`.
  final double focusedTaskResizeHandleWidth;

  /// Whether to show cursors from other users when connected via [syncClient].
  final bool showCursors;

  /// Whether to highlight the critical path on the chart.
  final bool showCriticalPath;

  /// Whether to show the resource histogram view below the chart.
  final bool showResourceHistogram;

  /// The calendar defining working days.
  final WorkCalendar? workCalendar;

  /// Whether to roll up milestones to summary tasks.
  final bool rollUpMilestones;

  /// Whether to show a vertical line indicating the current time ("now").
  final bool showNowLine;

  /// The specific date/time for the "now" line. If null, defaults to [DateTime.now()].
  final DateTime? nowLineDate;

  /// Whether to show the "safe zone" (slack/float) for each task.
  final bool showSlack;

  const LegacyGanttChartWidget({
    super.key, // Use super.key
    this.data,
    this.dependencies,
    this.conflictIndicators,
    this.holidays,
    required this.visibleRows,
    required this.rowMaxStackDepth,
    this.onTaskHover,
    this.scrollController,
    this.axisHeight,
    this.rowHeight = 27.0,
    this.onPressTask,
    this.theme,
    this.gridMin,
    this.gridMax,
    this.totalGridMin,
    this.totalGridMax,
    this.enableDragAndDrop = false,
    this.enableResize = false,
    this.tasksFuture,
    this.holidaysFuture,
    this.controller,
    this.taskBarBuilder,
    this.taskContentBuilder,
    this.onTaskUpdate,
    this.onTaskMove,
    this.onTaskDoubleClick,
    this.onTaskDelete,
    this.resizeTooltipDateFormat,
    this.onEmptySpaceClick,
    this.onTaskDrawEnd,
    this.onDependencyAdd,
    this.onTaskSecondaryTap,
    this.onTaskLongPress,
    this.resizeTooltipBackgroundColor,
    this.resizeTooltipFontColor,
    this.resizeHandleWidth = 10.0,
    this.timelineAxisLabelBuilder,
    this.timelineAxisHeaderBuilder,
    this.timelineViewMode = TimelineViewMode.auto,
    this.timelineLabelPlacement,
    this.gridLineStrokeWidth = 1.0,
    this.majorGridLineStrokeWidth = 2.0,
    this.emptyStateBuilder,
    this.showEmptyRows = false,
    this.onBulkTaskUpdate,
    this.onVisibleRangeChanged,
    this.enableVerticalTaskDrag = false,
    this.height,
    this.loadingIndicatorType = GanttLoadingIndicatorType.circular,
    this.loadingIndicatorPosition = GanttLoadingIndicatorPosition.top,
    this.linearProgressHeight = 4.0,
    this.weekendDays = const [DateTime.saturday, DateTime.sunday],
    this.weekendColor,
    this.onRowRequestVisible,
    this.focusedTaskId,
    this.onFocusChange,
    this.horizontalScrollController,
    this.horizontalZoomFactor = 1.0,
    this.horizontalZoomMin = 1.0,
    this.horizontalZoomMax = 8.0,
    this.allowHorizontalZoomGestures = true,
    this.onHorizontalZoomFactorChanged,
    this.focusedTaskResizeHandleBuilder,
    this.focusedTaskResizeHandleWidth = 24.0,
    this.syncClient,
    this.taskGrouper,
    this.showCursors = true,
    this.showCriticalPath = false,
    this.showResourceHistogram = false,
    this.workCalendar,
    this.rollUpMilestones = false,
    this.showNowLine = false,
    this.nowLineDate,
    this.showSlack = false,
  })  : assert(controller != null || ((data != null && tasksFuture == null) || (data == null && tasksFuture != null))),
        assert(controller == null || dependencies == null),
        assert(taskBarBuilder == null || taskContentBuilder == null),
        assert(controller == null || conflictIndicators == null),
        assert(controller == null ||
            (data == null &&
                tasksFuture == null &&
                holidays == null &&
                holidaysFuture == null &&
                gridMin == null &&
                gridMax == null)),
        assert(horizontalZoomMin >= 1.0),
        assert(horizontalZoomMax > horizontalZoomMin),
        assert(horizontalZoomFactor >= horizontalZoomMin && horizontalZoomFactor <= horizontalZoomMax);

  @override
  State<LegacyGanttChartWidget> createState() => _LegacyGanttChartWidgetState();
}

class _LegacyGanttChartWidgetState extends State<LegacyGanttChartWidget> {
  LegacyGanttViewModel? _internalViewModel;

  static const double _horizontalZoomScrollEpsilon = 1.0001;

  late double _horizontalZoom;
  ScrollController? _ownedHorizontalScrollController;
  double? _pinchZoomStartFactor;

  ScrollController get _horizontalScroll =>
      widget.horizontalScrollController ?? _ownedHorizontalScrollController!;

  double _clampZoom(double z) => z.clamp(widget.horizontalZoomMin, widget.horizontalZoomMax);

  @override
  void initState() {
    super.initState();
    _horizontalZoom = _clampZoom(widget.horizontalZoomFactor);
    if (widget.horizontalScrollController == null) {
      _ownedHorizontalScrollController = ScrollController();
    }
  }

  @override
  void dispose() {
    _ownedHorizontalScrollController?.dispose();
    super.dispose();
  }

  void _preserveHorizontalScrollAnchor(double previousZoom, double newZoom, double viewportWidth) {
    if (previousZoom <= 0 || viewportWidth <= 0) return;
    final controller = _horizontalScroll;
    final prevContentW = viewportWidth * previousZoom;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!controller.hasClients) return;
      final pos = controller.position;
      final center = pos.pixels + pos.viewportDimension * 0.5;
      final ratio = (center / prevContentW).clamp(0.0, 1.0);
      final newContentW = viewportWidth * newZoom;
      final target = ratio * newContentW - pos.viewportDimension * 0.5;
      controller.jumpTo(target.clamp(pos.minScrollExtent, pos.maxScrollExtent));
    });
  }

  void _applyHorizontalZoomGesture(double newZoom, double viewportWidth) {
    final prev = _horizontalZoom;
    final clamped = _clampZoom(newZoom);
    if ((clamped - prev).abs() < 1e-6) return;
    _preserveHorizontalScrollAnchor(prev, clamped, viewportWidth);
    setState(() => _horizontalZoom = clamped);
    widget.onHorizontalZoomFactorChanged?.call(clamped);
  }

  @override
  void didUpdateWidget(covariant LegacyGanttChartWidget oldWidget) {
    super.didUpdateWidget(oldWidget);

    if (widget.horizontalZoomFactor != oldWidget.horizontalZoomFactor ||
        widget.horizontalZoomMin != oldWidget.horizontalZoomMin ||
        widget.horizontalZoomMax != oldWidget.horizontalZoomMax) {
      _horizontalZoom = _clampZoom(widget.horizontalZoomFactor);
    }

    if (_internalViewModel != null) {
      _internalViewModel!.updateDependencies(widget.dependencies ?? []);

      if (oldWidget.showCursors != widget.showCursors) {
        _internalViewModel!.showRemoteCursors = widget.showCursors;
      }

      final List<LegacyGanttTask> allItems = [...(widget.data ?? []), ...(widget.holidays ?? [])];
      _internalViewModel!.updateData(allItems);

      if (widget.conflictIndicators != null) {
        _internalViewModel!.updateConflictIndicators(widget.conflictIndicators!);
      }

      if (oldWidget.workCalendar != widget.workCalendar) {
        _internalViewModel!.workCalendar = widget.workCalendar;
      }

      _internalViewModel!.updateVisibleRows(widget.visibleRows);

      _internalViewModel!.updateRowMaxStackDepth(widget.rowMaxStackDepth);

      if (oldWidget.axisHeight != widget.axisHeight) {
        _internalViewModel!.updateAxisHeight(widget.axisHeight);
      }

      if (oldWidget.totalGridMin != widget.totalGridMin || oldWidget.totalGridMax != widget.totalGridMax) {
        _internalViewModel!.updateTotalGridRange(widget.totalGridMin, widget.totalGridMax);
      }

      if (oldWidget.gridMin != widget.gridMin || oldWidget.gridMax != widget.gridMax) {
        _internalViewModel!.minMaxOverrides(widget.gridMin, widget.gridMax);
      }

      if (oldWidget.showCriticalPath != widget.showCriticalPath) {
        _internalViewModel!.showCriticalPath = widget.showCriticalPath;
      }

      if (oldWidget.workCalendar != widget.workCalendar) {
        _internalViewModel!.workCalendar = widget.workCalendar;
      }

      if (oldWidget.rollUpMilestones != widget.rollUpMilestones) {
        _internalViewModel!.rollUpMilestones = widget.rollUpMilestones;
      }

      if (oldWidget.showSlack != widget.showSlack) {
        _internalViewModel!.showSlack = widget.showSlack;
      }

      _internalViewModel!.onBulkTaskUpdate = widget.onBulkTaskUpdate;
      _internalViewModel!.onTaskHover = widget.onTaskHover;
      _internalViewModel!.onTaskLongPress = widget.onTaskLongPress;
    }
  }

  /// Helper method to determine what to show when there is no data.
  /// This centralizes the logic to avoid code duplication.
  Widget _buildEmptyView(BuildContext context, LegacyGanttTheme theme) {
    if (widget.emptyStateBuilder != null) {
      return widget.emptyStateBuilder!(context);
    }
    return Center(
      child: Text(
        'No data to display.',
        style: TextStyle(color: theme.textColor),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final LegacyGanttTheme effectiveTheme =
        (widget.theme ?? LegacyGanttTheme.fromTheme(theme)).copyWith(weekendColor: widget.weekendColor);

    if (widget.controller != null) {
      return _wrap(AnimatedBuilder(
        animation: widget.controller!,
        builder: (context, child) {
          final controller = widget.controller!;
          final tasks = controller.tasks;
          final holidays = controller.holidays;
          final dependencies = controller.dependencies;
          final conflictIndicators = controller.conflictIndicators;
          final allItems = [...tasks, ...holidays]; // Conflicts are handled separately

          if (_internalViewModel != null) {
            _internalViewModel!.updateData(allItems);
            _internalViewModel!.updateDependencies(dependencies);
            _internalViewModel!.updateConflictIndicators(conflictIndicators);
            _internalViewModel!.updateVisibleRange(controller.visibleStartDate.millisecondsSinceEpoch.toDouble(),
                controller.visibleEndDate.millisecondsSinceEpoch.toDouble());
          }

          if (controller.isOverallLoading && allItems.isEmpty && !widget.showEmptyRows) {
            if (widget.loadingIndicatorType == GanttLoadingIndicatorType.circular) {
              return const Center(child: CircularProgressIndicator());
            } else {
              return SizedBox(height: widget.linearProgressHeight, child: const LinearProgressIndicator());
            }
          }

          if (allItems.isEmpty && !controller.isOverallLoading && !widget.showEmptyRows) {
            return _buildEmptyView(context, effectiveTheme);
          }

          return Stack(
            children: [
              _buildChart(
                context,
                allItems,
                dependencies,
                conflictIndicators,
                effectiveTheme,
                gridMin: controller.visibleStartDate.millisecondsSinceEpoch.toDouble(),
                gridMax: controller.visibleEndDate.millisecondsSinceEpoch.toDouble(),
                currentTool: controller.currentTool,
              ),
              if (controller.isLoading && widget.loadingIndicatorType == GanttLoadingIndicatorType.linear)
                Positioned(
                  left: 0,
                  right: 0,
                  top: widget.loadingIndicatorPosition == GanttLoadingIndicatorPosition.top ? 0 : null,
                  bottom: widget.loadingIndicatorPosition == GanttLoadingIndicatorPosition.bottom ? 0 : null,
                  child: SizedBox(height: widget.linearProgressHeight, child: const LinearProgressIndicator()),
                ),
              if (controller.isLoading && widget.loadingIndicatorType == GanttLoadingIndicatorType.circular)
                Positioned.fill(
                  child: Container(
                    color: effectiveTheme.backgroundColor.withValues(alpha: 0.5),
                    child: const Center(child: CircularProgressIndicator()),
                  ),
                ),
            ],
          );
        },
      ));
    }

    if (widget.tasksFuture != null || widget.holidaysFuture != null) {
      return _wrap(FutureBuilder<List<dynamic>>(
        future: Future.wait([
          widget.tasksFuture ?? Future.value(<LegacyGanttTask>[]),
          widget.holidaysFuture ?? Future.value(<LegacyGanttTask>[])
        ]),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          }
          final tasks = (snapshot.data?[0] as List<LegacyGanttTask>?) ?? [];
          final holidays = (snapshot.data?[1] as List<LegacyGanttTask>?) ?? [];
          final allItems = [...tasks, ...holidays];
          final conflictIndicators = widget.conflictIndicators ?? [];
          if (allItems.isEmpty && !widget.showEmptyRows) {
            return _buildEmptyView(context, effectiveTheme);
          }
          return _wrap(_buildChart(context, allItems, widget.dependencies ?? [], conflictIndicators, effectiveTheme));
        },
      ));
    } else {
      final tasks = widget.data ?? [];
      final holidays = widget.holidays ?? [];
      final conflictIndicators = widget.conflictIndicators ?? [];
      final allItems = [...tasks, ...holidays];
      if (allItems.isEmpty && !widget.showEmptyRows) {
        return _wrap(_buildEmptyView(context, effectiveTheme));
      }
      return _wrap(_buildChart(context, allItems, widget.dependencies ?? [], conflictIndicators, effectiveTheme));
    }
  }

  Widget _buildChart(BuildContext context, List<LegacyGanttTask> tasks, List<LegacyGanttTaskDependency> dependencies,
          List<LegacyGanttTask> conflictIndicators, LegacyGanttTheme effectiveTheme,
          {double? gridMin, double? gridMax, GanttTool currentTool = GanttTool.move}) =>
      ChangeNotifierProvider<LegacyGanttViewModel>(
        key: ValueKey(widget.syncClient),
        create: (context) {
          _internalViewModel = LegacyGanttViewModel(
            data: tasks,
            conflictIndicators: conflictIndicators,
            dependencies: dependencies,
            visibleRows: widget.visibleRows,
            rowMaxStackDepth: widget.rowMaxStackDepth,
            rowHeight: widget.rowHeight,
            axisHeight: widget.axisHeight,
            gridMin: gridMin ?? widget.gridMin,
            gridMax: gridMax ?? widget.gridMax,
            totalGridMin: widget.totalGridMin,
            totalGridMax: widget.totalGridMax,
            enableDragAndDrop: widget.enableDragAndDrop,
            enableResize: widget.enableResize,
            enableVerticalTaskDrag: widget.enableVerticalTaskDrag,
            onTaskUpdate: widget.onTaskUpdate,
            onTaskMove: widget.onTaskMove,
            onTaskDoubleClick: widget.onTaskDoubleClick,
            onTaskDelete: widget.onTaskDelete,
            onEmptySpaceClick: widget.onEmptySpaceClick,
            onTaskDrawEnd: widget.onTaskDrawEnd,
            onDependencyAdd: (dependency) {
              if (widget.controller != null) {
                widget.controller!.addDependency(dependency);
              }
              widget.onDependencyAdd?.call(dependency);
            },
            onPressTask: widget.onPressTask,
            onTaskHover: widget.onTaskHover,
            onTaskSecondaryTap: widget.onTaskSecondaryTap,
            onTaskLongPress: widget.onTaskLongPress,
            taskBarBuilder: widget.taskBarBuilder,
            resizeTooltipDateFormat: widget.resizeTooltipDateFormat,
            scrollController: widget.scrollController,
            ganttHorizontalScrollController: widget.horizontalScrollController,
            onRowRequestVisible: widget.onRowRequestVisible,
            initialFocusedTaskId: widget.focusedTaskId,
            onFocusChange: widget.onFocusChange,
            resizeHandleWidth: widget.resizeHandleWidth,
            syncClient: widget.syncClient,
            taskGrouper: widget.taskGrouper ?? (task) => task.resourceId,
            workCalendar: widget.workCalendar,
            rollUpMilestones: widget.rollUpMilestones,
            showSlack: widget.showSlack,
            onBulkTaskUpdate: widget.onBulkTaskUpdate,
            onVisibleRangeChanged: widget.onVisibleRangeChanged,
            onSelectionChanged: (ids) {
              if (widget.controller != null) {
                widget.controller!.setSelectedTaskIds(ids);
              }
            },
          )
            ..showRemoteCursors = widget.showCursors
            ..showCriticalPath = widget.showCriticalPath;
          return _internalViewModel!;
        },
        child: Consumer<LegacyGanttViewModel>(
          builder: (context, vm, child) {
            SchedulerBinding.instance.addPostFrameCallback((_) {
              if (!vm.isDisposed) {
                vm.updateVisibleRange(gridMin ?? widget.gridMin, gridMax ?? widget.gridMax);
                vm.updateFocusedTask(widget.focusedTaskId);
                vm.updateResizeTooltipDateFormat(widget.resizeTooltipDateFormat);
                vm.setTool(currentTool);
              }
            });

            return Column(
              children: [
                Expanded(
                  child: LayoutBuilder(
                    builder: (BuildContext context, BoxConstraints constraints) {
                      if (constraints.maxWidth == 0 || constraints.maxHeight == 0) {
                        return const SizedBox.shrink();
                      }

                      final double viewportW = constraints.maxWidth;
                      final double zoom = _horizontalZoom;
                      final double timelineW = viewportW * zoom;

                      vm.updateLayout(timelineW, constraints.maxHeight);

                      final double totalContentWidth =
                          vm.totalDomain.isEmpty ? timelineW : vm.totalScale(vm.totalDomain.last);

                      final double totalContentHeight = widget.visibleRows
                          .where((row) => widget.showEmptyRows || (vm.tasksByRow[row.id]?.isNotEmpty ?? false))
                          .fold<double>(
                            0.0,
                            (prev, row) => prev + widget.rowHeight * (widget.rowMaxStackDepth[row.id] ?? 1),
                          );

                      final bool useIntrinsicHeight = !constraints.maxHeight.isFinite;
                      final double chartHeight;

                      if (widget.height != null) {
                        chartHeight = widget.height!;
                      } else if (useIntrinsicHeight) {
                        chartHeight = vm.timeAxisHeight + totalContentHeight;
                      } else {
                        chartHeight = constraints.maxHeight;
                      }
                      final double contentHeight = chartHeight - vm.timeAxisHeight;

                      final double layoutHeight =
                          constraints.maxHeight.isFinite ? constraints.maxHeight : chartHeight;
                      final double paintWidth = timelineW;
                      final double paintHeightBelowAxis = layoutHeight - vm.timeAxisHeight;

                      Widget chartArea = Column(
                        children: [
                          Expanded(
                            child: Listener(
                              onPointerDown: vm.onPointerEvent,
                              onPointerUp: vm.onPointerEvent,
                              onPointerCancel: vm.onPointerEvent,
                              onPointerPanZoomStart: widget.allowHorizontalZoomGestures
                                  ? (PointerPanZoomStartEvent e) {
                                      _pinchZoomStartFactor = _horizontalZoom;
                                    }
                                  : null,
                              onPointerPanZoomUpdate: widget.allowHorizontalZoomGestures
                                  ? (PointerPanZoomUpdateEvent e) {
                                      final base = _pinchZoomStartFactor;
                                      if (base == null) return;
                                      _applyHorizontalZoomGesture(base * e.scale, viewportW);
                                    }
                                  : null,
                              onPointerPanZoomEnd: widget.allowHorizontalZoomGestures
                                  ? (PointerPanZoomEndEvent e) {
                                      _pinchZoomStartFactor = null;
                                    }
                                  : null,
                              onPointerSignal: (event) {
                                if (event is PointerScrollEvent) {
                                  final keyboard = HardwareKeyboard.instance;
                                  final zoomModifier = widget.allowHorizontalZoomGestures &&
                                      (keyboard.isControlPressed || keyboard.isMetaPressed);
                                  if (zoomModifier && event.scrollDelta.dy != 0) {
                                    final mult = event.scrollDelta.dy > 0 ? 1 / 1.1 : 1.1;
                                    _applyHorizontalZoomGesture(_horizontalZoom * mult, viewportW);
                                    return;
                                  }
                                  if (event.scrollDelta.dx != 0) {
                                    vm.onHorizontalScroll(event.scrollDelta.dx);
                                  }
                                  if (event.scrollDelta.dy != 0) {
                                    if (vm.scrollController != null && vm.scrollController!.hasClients) {
                                      final newOffset = vm.scrollController!.offset + event.scrollDelta.dy;
                                      vm.scrollController!.jumpTo(newOffset.clamp(
                                          vm.scrollController!.position.minScrollExtent,
                                          vm.scrollController!.position.maxScrollExtent));
                                    }
                                  }
                                }
                              },
                              child: GestureDetector(
                                onPanStart: (details) => vm.onPanStart(details),
                                onPanUpdate: (details) => vm.onPanUpdate(details),
                                onPanEnd: (details) => vm.onPanEnd(details),
                                onTapDown: (details) => vm.onTapDown(details),
                                onTap: () => vm.onTap(),
                                onSecondaryTapUp: (details) =>
                                    vm.onSecondaryTap(details.localPosition, details.globalPosition),
                                onLongPressStart: (details) =>
                                    vm.onLongPress(details.localPosition, details.globalPosition),
                                onDoubleTapDown: (details) => vm.onDoubleTap(details.localPosition),
                                child: MouseRegion(
                                  cursor: vm.cursor,
                                  onHover: (event) => vm.onHover(event),
                                  onExit: (event) => vm.onHoverExit(event),
                                  child: ClipRect(
                                    child: Stack(
                                      children: [
                                        Padding(
                                          padding: EdgeInsets.only(top: vm.timeAxisHeight),
                                          child: Stack(
                                            children: [
                                              RepaintBoundary(
                                                child: CustomPaint(
                                                  size: Size(paintWidth, paintHeightBelowAxis),
                                                  painter: AxisPainter(
                                                    x: 0,
                                                    y: 0,
                                                    width: totalContentWidth,
                                                    height: contentHeight,
                                                    scale: vm.totalScale,
                                                    domain: vm.totalDomain,
                                                    visibleDomain: vm.visibleExtent,
                                                    theme: effectiveTheme.copyWith(
                                                        axisTextStyle: const TextStyle(color: Colors.transparent)),
                                                    weekendColor: effectiveTheme.weekendColor,
                                                    weekendDays:
                                                        widget.workCalendar?.weekendDays.toList() ?? widget.weekendDays,
                                                    timelineViewMode: widget.timelineViewMode,
                                                    labelPlacement: widget.timelineLabelPlacement,
                                                    gridLineStrokeWidth: widget.gridLineStrokeWidth,
                                                    majorGridLineStrokeWidth: widget.majorGridLineStrokeWidth,
                                                  ),
                                                ),
                                              ),
                                              RepaintBoundary(
                                                child: CustomPaint(
                                                  size: Size(paintWidth, paintHeightBelowAxis),
                                                  painter: BarsCollectionPainter(
                                                    tasksByRow: vm.tasksByRow,
                                                    conflictIndicators: vm.conflictIndicators,
                                                    dependencies: vm.dependencies,
                                                    data: vm.data,
                                                    domain: vm.totalDomain,
                                                    visibleRows: widget.visibleRows,
                                                    rowMaxStackDepth: widget.rowMaxStackDepth,
                                                    scale: vm.totalScale,
                                                    rowHeight: widget.rowHeight,
                                                    draggedTaskId: vm.draggedTask?.id,
                                                    drawingTask:
                                                        vm.currentTool == GanttTool.draw ? vm.draggedTask : null,
                                                    ghostTaskStart: vm.ghostTaskStart,
                                                    ghostTaskEnd: vm.ghostTaskEnd,
                                                    ghostTaskRowId: vm.ghostTaskRowId,
                                                    remoteGhosts: vm.remoteGhosts,
                                                    theme: effectiveTheme,
                                                    hoveredRowId: vm.hoveredRowId,
                                                    hoveredDate: vm.hoveredDate,
                                                    cpmStats: vm.cpmStats,
                                                    showSlack: vm.showSlack,
                                                    hasCustomTaskBuilder: widget.taskBarBuilder != null,
                                                    hasCustomTaskContentBuilder: widget.taskContentBuilder != null,
                                                    translateY: vm.translateY,
                                                    selectedTaskIds: vm.selectedTaskIds,
                                                    bulkGhostTasks: vm.bulkGhostTasks,
                                                    rollUpMilestones: widget.rollUpMilestones,
                                                    enableDependencyCreation:
                                                        vm.currentTool == GanttTool.drawDependencies,
                                                    dependencyDragStartTaskId: vm.dependencyStartTaskId,
                                                    dependencyDragStartIsFromStart:
                                                        vm.dependencyStartSide == TaskPart.startHandle,
                                                    dependencyDragCurrentPosition: vm.currentDragPosition,
                                                    hoveredTaskForDependency: vm.dependencyHoveredTaskId,
                                                    criticalTaskIds: vm.criticalTaskIds,
                                                    criticalDependencies: vm.criticalDependencies,
                                                    workCalendar: vm.workCalendar,
                                                    showNowLine: widget.showNowLine,
                                                    nowLineDate: widget.nowLineDate,
                                                    dependencyDragStatus: vm.dependencyDragStatus,
                                                    dependencyDragDelayAmount: vm.dependencyDragDelayAmount,
                                                  ),
                                                ),
                                              ),
                                              if (vm.currentTool == GanttTool.select && vm.selectionRect != null)
                                                CustomPaint(
                                                  size: Size(paintWidth, paintHeightBelowAxis),
                                                  painter: _SelectionBoxPainter(
                                                    rect: vm.selectionRect!,
                                                    borderColor: Theme.of(context).primaryColor,
                                                    fillColor: Theme.of(context).primaryColor.withValues(alpha: 0.2),
                                                  ),
                                                ),
                                              if (widget.taskBarBuilder != null || widget.taskContentBuilder != null)
                                                ..._buildTaskWidgets(vm, vm.data, effectiveTheme),
                                              ..._buildCustomCellWidgets(vm, vm.data),
                                              ..._buildFocusedTaskWidgets(
                                                  vm,
                                                  vm.data,
                                                  effectiveTheme,
                                                  widget.focusedTaskResizeHandleBuilder,
                                                  widget.focusedTaskResizeHandleWidth),
                                              if (vm.showRemoteCursors)
                                                IgnorePointer(
                                                  child: RepaintBoundary(
                                                    child: CustomPaint(
                                                      size: Size(paintWidth, paintHeightBelowAxis),
                                                      painter: CursorPainter(
                                                        remoteCursors:
                                                            vm.showRemoteCursors ? vm.remoteCursors : const {},
                                                        totalScale: vm.totalScale,
                                                        visibleRows: widget.visibleRows,
                                                        rowMaxStackDepth: widget.rowMaxStackDepth,
                                                        rowHeight: widget.rowHeight,
                                                        translateY: vm.translateY,
                                                      ),
                                                    ),
                                                  ),
                                                ),
                                            ],
                                          ),
                                        ),
                                        Positioned(
                                          top: 0,
                                          left: 0,
                                          right: 0,
                                          height: vm.timeAxisHeight,
                                          child: widget.timelineAxisHeaderBuilder != null
                                              ? widget.timelineAxisHeaderBuilder!(
                                                  context,
                                                  vm.totalScale,
                                                  vm.visibleExtent,
                                                  vm.totalDomain,
                                                  effectiveTheme,
                                                  totalContentWidth,
                                                )
                                              : Container(
                                                  color: effectiveTheme.backgroundColor,
                                                  child: RepaintBoundary(
                                                    child: CustomPaint(
                                                      painter: AxisPainter(
                                                        x: 0,
                                                        y: 0,
                                                        width: totalContentWidth,
                                                        height: vm.timeAxisHeight,
                                                        scale: vm.totalScale,
                                                        domain: vm.totalDomain,
                                                        visibleDomain: vm.visibleExtent,
                                                        theme: effectiveTheme,
                                                        timelineAxisLabelBuilder: widget.timelineAxisLabelBuilder,
                                                        weekendColor: effectiveTheme.weekendColor,
                                                        weekendDays: widget.workCalendar?.weekendDays.toList() ??
                                                            widget.weekendDays,
                                                        showGridLines: false,
                                                        verticallyCenterLabels: true,
                                                        timelineViewMode: widget.timelineViewMode,
                                                        labelPlacement: widget.timelineLabelPlacement,
                                                        gridLineStrokeWidth: widget.gridLineStrokeWidth,
                                                        majorGridLineStrokeWidth: widget.majorGridLineStrokeWidth,
                                                      ),
                                                    ),
                                                  ),
                                                ),
                                        ),
                                        if (vm.showResizeTooltip)
                                          Positioned(
                                            left: vm.resizeTooltipPosition.dx + 15,
                                            top: vm.resizeTooltipPosition.dy + 15,
                                            child: _buildResizeTooltip(context, vm.resizeTooltipText, effectiveTheme),
                                          ),
                                      ],
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                          if (widget.showResourceHistogram) ...[
                            const Divider(height: 1),
                            ResourceHistogramWidget(
                              viewModel: vm,
                              height: 150,
                              theme: effectiveTheme,
                            ),
                          ],
                        ],
                      );

                      if (zoom > _horizontalZoomScrollEpsilon) {
                        return SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          primary: false,
                          controller: _horizontalScroll,
                          child: SizedBox(
                            width: timelineW,
                            height: layoutHeight,
                            child: chartArea,
                          ),
                        );
                      }
                      return SizedBox(
                        width: viewportW,
                        height: layoutHeight,
                        child: chartArea,
                      );
                    },
                  ),
                ),
              ],
            );
          },
        ),
      );

  Widget _wrap(Widget child) {
    if (widget.height != null) {
      return SizedBox(height: widget.height, child: child);
    }
    return child;
  }

  Widget _buildResizeTooltip(BuildContext context, String text, LegacyGanttTheme theme) {
    final tooltipBackgroundColor = widget.resizeTooltipBackgroundColor ?? theme.barColorPrimary;
    final tooltipFontColor = widget.resizeTooltipFontColor ??
        (ThemeData.estimateBrightnessForColor(tooltipBackgroundColor) == Brightness.dark ? Colors.white : Colors.black);

    return Material(
      elevation: 4.0,
      borderRadius: BorderRadius.circular(4),
      color: Colors.transparent,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
        decoration: BoxDecoration(color: tooltipBackgroundColor, borderRadius: BorderRadius.circular(4)),
        child: Text(
          text,
          style: theme.axisTextStyle.copyWith(color: tooltipFontColor),
        ),
      ),
    );
  }

  List<Widget> _buildTaskWidgets(LegacyGanttViewModel vm, List<LegacyGanttTask> tasks, LegacyGanttTheme theme) {
    final List<Widget> taskWidgets = [];
    double cumulativeRowTop = 0;
    final draggedTask = vm.draggedTask;
    final shouldRenderDraggedTaskSeparately =
        draggedTask != null && vm.ghostTaskStart != null && vm.ghostTaskEnd != null;

    for (final rowData in vm.visibleRows) {
      final tasksInThisRow = vm.tasksByRow[rowData.id];

      if (tasksInThisRow != null) {
        for (final task in tasksInThisRow) {
          if (shouldRenderDraggedTaskSeparately && draggedTask.id == task.id) {
            continue;
          }

          if (task.isTimeRangeHighlight) continue;

          final startX = vm.totalScale(task.start);
          final endX = vm.totalScale(task.end);
          final width = endX - startX;

          if (width <= 0) {
            continue;
          }

          final top = cumulativeRowTop + (task.stackIndex * vm.rowHeight) + vm.translateY;

          Widget taskWidget;
          if (task.isOverlapIndicator) {
            taskWidget = _OverlapIndicatorBar(theme: theme);
          } else if (widget.taskBarBuilder != null) {
            taskWidget = widget.taskBarBuilder!(task);
          } else {
            if (widget.taskContentBuilder == null) {
              continue;
            }

            taskWidget = _DefaultTaskBar(
              task: task,
              vm: vm,
              theme: theme,
              content: widget.taskContentBuilder!(task),
            );
          }

          taskWidgets.add(Positioned(
            left: startX,
            top: top,
            width: width,
            height: vm.rowHeight,
            child: taskWidget,
          ));
        }
      }
      final stackDepth = vm.rowMaxStackDepth[rowData.id] ?? 1;
      cumulativeRowTop += vm.rowHeight * stackDepth;
    }

    if (shouldRenderDraggedTaskSeparately) {
      final ghostRowId = vm.ghostTaskRowId ?? draggedTask.rowId;
      final rowIndex = vm.visibleRows.indexWhere((row) => row.id == ghostRowId);
      final rowTop = rowIndex == -1 ? null : vm.getRowVerticalOffset(rowIndex);

      if (rowTop != null) {
        final startX = vm.totalScale(vm.ghostTaskStart!);
        final endX = vm.totalScale(vm.ghostTaskEnd!);
        final width = endX - startX;

        if (width > 0) {
          Widget taskWidget;
          if (draggedTask.isOverlapIndicator) {
            taskWidget = _OverlapIndicatorBar(theme: theme);
          } else if (widget.taskBarBuilder != null) {
            taskWidget = widget.taskBarBuilder!(draggedTask);
          } else {
            if (widget.taskContentBuilder == null) {
              return taskWidgets;
            }

            taskWidget = _DefaultTaskBar(
              task: draggedTask,
              vm: vm,
              theme: theme,
              content: widget.taskContentBuilder!(draggedTask),
            );
          }

          taskWidgets.add(
            Positioned(
              left: startX,
              top: rowTop + (draggedTask.stackIndex * vm.rowHeight) + vm.translateY,
              width: width,
              height: vm.rowHeight,
              child: taskWidget,
            ),
          );
        }
      }
    }

    return taskWidgets;
  }

  List<Widget> _buildCustomCellWidgets(LegacyGanttViewModel vm, List<LegacyGanttTask> tasks) {
    final List<Widget> customCells = [];
    double cumulativeRowTop = 0;

    for (final rowData in vm.visibleRows) {
      final tasksInThisRow = vm.tasksByRow[rowData.id];

      if (tasksInThisRow != null) {
        for (final task in tasksInThisRow) {
          if (task.cellBuilder == null) continue;

          final taskStart = task.start;
          final taskEnd = task.end;
          var currentDate = DateTime(taskStart.year, taskStart.month, taskStart.day);

          while (currentDate.isBefore(taskEnd)) {
            final segmentStart = taskStart.isAfter(currentDate) ? taskStart : currentDate;

            final nextDay = currentDate.add(const Duration(days: 1));
            final segmentEnd = taskEnd.isBefore(nextDay) ? taskEnd : nextDay;

            final startX = vm.totalScale(segmentStart);
            final endX = vm.totalScale(segmentEnd);
            final width = endX - startX;

            if (width > 0) {
              final top = cumulativeRowTop + (task.stackIndex * vm.rowHeight) + vm.translateY;
              customCells.add(Positioned(
                  left: startX, top: top, width: width, height: vm.rowHeight, child: task.cellBuilder!(currentDate)));
            }
            currentDate = nextDay;
          }
        }
      }
      final stackDepth = vm.rowMaxStackDepth[rowData.id] ?? 1;
      cumulativeRowTop += vm.rowHeight * stackDepth;
    }
    return customCells;
  }
}

List<Widget> _buildFocusedTaskWidgets(
  LegacyGanttViewModel vm,
  List<LegacyGanttTask> tasks,
  LegacyGanttTheme theme,
  Widget Function(LegacyGanttTask, TaskPart, LegacyGanttViewModel, double)? handleBuilder,
  double handleWidth,
) {
  if (vm.focusedTaskId == null) return [];

  final focusedTask = tasks.firstWhere((t) => t.id == vm.focusedTaskId, orElse: () => LegacyGanttTask.empty());
  if (focusedTask.id.isEmpty) return [];

  final effectiveRowId =
      vm.draggedTask?.id == focusedTask.id && vm.ghostTaskRowId != null ? vm.ghostTaskRowId! : focusedTask.rowId;
  final effectiveStart = vm.draggedTask?.id == focusedTask.id && vm.ghostTaskStart != null ? vm.ghostTaskStart! : focusedTask.start;
  final effectiveEnd = vm.draggedTask?.id == focusedTask.id && vm.ghostTaskEnd != null ? vm.ghostTaskEnd! : focusedTask.end;
  final effectiveRowIndex = vm.visibleRows.indexWhere((r) => r.id == effectiveRowId);
  if (effectiveRowIndex == -1) return [];

  final rowTop = vm.getRowVerticalOffset(effectiveRowIndex);
  if (rowTop == null) return [];

  final startX = vm.totalScale(effectiveStart);
  final endX = vm.totalScale(effectiveEnd);
  final width = endX - startX;
  final top = rowTop + (focusedTask.stackIndex * vm.rowHeight) + vm.translateY;

  final List<Widget> widgets = [
    Positioned(
      left: startX,
      top: top,
      width: width,
      height: vm.rowHeight,
      child: IgnorePointer(
        child: Container(
          decoration: BoxDecoration(
            border: Border.all(color: theme.barColorSecondary, width: 2),
            borderRadius: BorderRadius.circular(4.0),
          ),
        ),
      ),
    )
  ];

  if (handleBuilder != null) {
    final startHandle = handleBuilder(focusedTask, TaskPart.startHandle, vm, handleWidth);
    final endHandle = handleBuilder(focusedTask, TaskPart.endHandle, vm, handleWidth);

    widgets.addAll([
      Positioned(
        left: startX - handleWidth,
        top: top,
        height: vm.rowHeight,
        child: startHandle,
      ),
      Positioned(
        left: endX,
        top: top,
        height: vm.rowHeight,
        child: endHandle,
      ),
    ]);
  }

  return widgets;
}

class _DefaultTaskBar extends StatefulWidget {
  final LegacyGanttTask task;
  final LegacyGanttViewModel vm;
  final LegacyGanttTheme theme;
  final Widget? content;

  const _DefaultTaskBar({
    required this.task,
    required this.vm,
    required this.theme,
    this.content,
  });

  @override
  _DefaultTaskBarState createState() => _DefaultTaskBarState();
}

class _DefaultTaskBarState extends State<_DefaultTaskBar> {
  bool _isHovered = false;
  final FocusNode _focusNode = FocusNode();

  @override
  void dispose() {
    _focusNode.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final task = widget.task;
    final theme = widget.theme;
    final vm = widget.vm;
    final content = widget.content;
    final barHeight = vm.rowHeight * theme.barHeightRatio;
    final verticalInset = (vm.rowHeight - barHeight) / 2;
    return Focus(
      focusNode: _focusNode,
      onFocusChange: (hasFocus) {
        if (hasFocus) {
          vm.setFocusedTask(task.id);
        }
      },
      child: MouseRegion(
        onEnter: (_) => setState(() => _isHovered = true),
        onExit: (_) => setState(() => _isHovered = false),
        child: Container(
          decoration: BoxDecoration(
            color: Colors.transparent,
            borderRadius: BorderRadius.circular(4.0),
          ),
          child: Stack(
            fit: StackFit.expand,
            children: [
              if (content != null)
                Positioned(
                  left: 0,
                  right: 0,
                  top: verticalInset,
                  height: barHeight,
                  child: ClipRRect(
                    borderRadius: BorderRadius.all(theme.barCornerRadius),
                    child: Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 4.0),
                      child: DefaultTextStyle(
                        style: theme.taskTextStyle,
                        maxLines: 1,
                        overflow: TextOverflow.ellipsis,
                        child: Align(
                          alignment: Alignment.centerLeft,
                          child: content,
                        ),
                      ),
                    ),
                  ),
                ),
              if (_isHovered && vm.onTaskDelete != null)
                Positioned(
                  right: 0,
                  top: 0,
                  bottom: 0,
                  child: IconButton(
                    icon: const Icon(Icons.close, size: 16),
                    color: theme.taskTextStyle.color,
                    onPressed: () => vm.deleteTask(task),
                    splashRadius: 16,
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

/// A widget that uses a [CustomPainter] to draw the conflict/overlap pattern.
class _OverlapIndicatorBar extends StatelessWidget {
  final LegacyGanttTheme theme;

  const _OverlapIndicatorBar({required this.theme});

  @override
  Widget build(BuildContext context) => CustomPaint(
        painter: _OverlapPainter(theme: theme),
        child: Container(),
      );
}

/// The actual painter for the conflict/overlap pattern.
class _OverlapPainter extends CustomPainter {
  final LegacyGanttTheme theme;

  _OverlapPainter({required this.theme});

  @override
  void paint(Canvas canvas, Size size) {
    final barHeight = size.height * theme.barHeightRatio;
    final barVerticalCenterOffset = (size.height - barHeight) / 2;
    final fullRect = Rect.fromLTWH(0, barVerticalCenterOffset, size.width, barHeight);

    final indicatorHeight = fullRect.height * 0.4;
    final indicatorRect = Rect.fromLTWH(
      fullRect.left,
      fullRect.bottom - indicatorHeight,
      fullRect.width,
      indicatorHeight,
    );
    final indicatorRRect = RRect.fromRectAndRadius(indicatorRect, theme.barCornerRadius);

    canvas.drawRRect(indicatorRRect, Paint()..color = theme.backgroundColor);

    final backgroundPaint = Paint()..color = theme.conflictBarColor.withValues(alpha: 0.4);
    canvas.drawRRect(indicatorRRect, backgroundPaint);

    _drawAngledPattern(canvas, indicatorRRect, theme.conflictBarColor, 1.0);
  }

  void _drawAngledPattern(Canvas canvas, RRect rrect, Color color, double strokeWidth) {
    final patternPaint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;

    canvas.save();
    canvas.clipRRect(rrect);

    const double lineSpacing = 8.0;
    for (double i = -rrect.height; i < rrect.width; i += lineSpacing) {
      canvas.drawLine(
          Offset(rrect.left + i, rrect.top), Offset(rrect.left + i + rrect.height, rrect.bottom), patternPaint);
    }
    canvas.restore();
  }

  @override
  bool shouldRepaint(covariant _OverlapPainter oldDelegate) => oldDelegate.theme != theme;
}

class _SelectionBoxPainter extends CustomPainter {
  final Rect rect;
  final Color borderColor;
  final Color fillColor;

  _SelectionBoxPainter({required this.rect, required this.borderColor, required this.fillColor});

  @override
  void paint(Canvas canvas, Size size) {
    canvas.drawRect(
      rect,
      Paint()
        ..color = fillColor
        ..style = PaintingStyle.fill,
    );
    canvas.drawRect(
      rect,
      Paint()
        ..color = borderColor
        ..style = PaintingStyle.stroke
        ..strokeWidth = 1,
    );
  }

  @override
  bool shouldRepaint(covariant _SelectionBoxPainter oldDelegate) =>
      rect != oldDelegate.rect || borderColor != oldDelegate.borderColor || fillColor != oldDelegate.fillColor;
}
